config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :receivers
  resources :conversations, only: [:index] do
    resources :messages, module: :conversations, only: [:index, :create, :destroy]
    resources :recurring_messages, controller: 'conversations/recurring_messages'
  end

  # Twilio webhook for inbound message
  post 'conversations/messages/reply', to: 'conversations/messages#reply'


  root 'receivers#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user
  belongs_to :receiver

  has_many :messages
  has_many :recurring_messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :conversation
  belongs_to :recurring_message, optional: true
end

app/models/receiver.rb
class Receiver < ApplicationRecord
  belongs_to :user
  has_one :conversation

  after_create :create_conversation

  def create_conversation
    Conversation.find_or_create_by(receiver: self, user: self.user)
  end

end

app/models/recurring_message.rb
class RecurringMessage < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
  has_many :messages
end

app/models/sms.rb
class SMS
  def initialize(to_phone_number)
    @to_phone_number = to_phone_number
  end

  def client
    Twilio::REST::Client.new Rails.application.credentials.twilio_account_sid, Rails.application.credentials.twilio_token
  end

  def send(body)
    client.messages.create(
      :messaging_service_sid => Rails.application.credentials.twilio_messaging_service_sid,
      :to => @to_phone_number,
      :body => body
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :receivers
  has_many :conversations 
  has_many :messages
  has_many :recurring_messages      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversations/messages_controller.rb
class Conversations::MessagesController < ApplicationController
  before_action :authenticate_user!, except: [:reply]
  before_action :set_conversation, except: [:reply]
  skip_before_action :verify_authenticity_token, only: [:reply]

  def index
    @messages = @conversation.messages.where(status: 'sent').or(@conversation.messages.where(status: 'received')).order("COALESCE(sent_at, created_at)")
    @pending_messages = @conversation.messages.where(status: 'pending').order("send_at ASC")
    @message = @conversation.messages.build
    @recurring_messages = @conversation.recurring_messages
  end

  def create
    @message = @conversation.messages.build(message_params)

    @message.update(to: @conversation.receiver.phone_number, status: 'pending', direction: 'outbound-api', user_id: @conversation.user.id)

    if @message.save
      SendSmsJob.perform_later(@message)
      # If has time scheduled, use perform_at else use existing
      #if @message.send_at != nil
        #Workaround for time zone, need to fix
      #  send_time = @message.send_at.advance(:hours => 4)
      #  SendSmsJob.set(wait_until: send_time).perform_later(@message)
      #else  
      #  SendSmsJob.perform_later(@message)
      #end
      redirect_to conversation_messages_path(@conversation), notice: 'Message sent'
    else
      redirect_to conversation_messages_path(@conversation), alert: 'Something went wrong'
    end
  end

  def reply
    # handle Twilio POST here
    from = params[:From].gsub(/^\+\d/, '')
    body = params[:Body]
    status = params[:SmsStatus]
    direction = 'inbound'
    message_sid = params[:MessageSid]

    # Find the conversation it should belong to.
    receiver = Receiver.find_by(phone_number: from)
    @conversation = Conversation.find_by(receiver: receiver)

    @message = @conversation.messages.build(body: body, direction: direction, status: status, from: from, message_sid: message_sid, user_id: @conversation.user.id)
    @message.save
    # the head :ok tells everything is ok
    # This stops template errors in the console
    head :ok, content_type: "text/html"

  end


  def destroy
    @conversation = Conversation.find(params[:conversation_id])
    @message = Message.find(params[:id])
    @message.destroy
    respond_to do |format|
      format.html { redirect_to conversation_messages_path(@conversation), notice: 'Recurring message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_conversation
      @conversation = current_user.conversations.find(params[:conversation_id])
    end

    def message_params
      params.require(:message).permit(:body, :send_at, :to, :from, :status, :message_sid, :account_sid, :messaging_service_sid, :direction, :user_id, :conversation_id, :sent_at, :recurring, :frequency, :recurring_message_id)
    end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @conversations = current_user.conversations.includes(:receiver).all
  end
end

app/controllers/receivers_controller.rb
class ReceiversController < ApplicationController
  before_action :set_receiver, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /receivers
  # GET /receivers.json
  def index
    @receivers = Receiver.all
  end

  # GET /receivers/1
  # GET /receivers/1.json
  def show
  end

  # GET /receivers/new
  def new
    @receiver = Receiver.new
  end

  # GET /receivers/1/edit
  def edit
  end

  # POST /receivers
  # POST /receivers.json
  def create
    @receiver = current_user.receivers.build(receiver_params)
    
    respond_to do |format|
      if @receiver.save
        format.html { redirect_to @receiver, notice: 'Receiver was successfully created.' }
        format.json { render :show, status: :created, location: @receiver }
      else
        format.html { render :new }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receivers/1
  # PATCH/PUT /receivers/1.json
  def update
    respond_to do |format|
      if @receiver.update(receiver_params)
        format.html { redirect_to @receiver, notice: 'Receiver was successfully updated.' }
        format.json { render :show, status: :ok, location: @receiver }
      else
        format.html { render :edit }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receivers/1
  # DELETE /receivers/1.json
  def destroy
    @receiver.destroy
    respond_to do |format|
      format.html { redirect_to receivers_url, notice: 'Receiver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receiver
      @receiver = Receiver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receiver_params
      params.require(:receiver).permit(:name, :phone_number, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/helpers/conversations/messages_helper.rb
module Conversations::MessagesHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/receivers_helper.rb
module ReceiversHelper
end

app/views/conversations/_conversation.html.erb
<div class="conversation">
  Receiver: <%= conversation.receiver.name %><br>
  <%= link_to "View Conversation", conversation_messages_path(conversation) %>
  <hr>
</div>

app/views/conversations/index.html.erb
<h1>Conversations</h1>
<%= render @conversations %>

app/views/conversations/messages/_message.html.erb
<div class="message clearfix <%= message.id %>" data-time="<%= message.created_at %>">
  <div class="alert <%= message.from ? 'alert-info message-inbound' : 'alert-success message-outbound' %>">
    <%= message.body %>
     <div class="text-right">
       <% if message.status == "sent" %><small>Sent</small><% end %>
       <% if message.sent_at %>
        <small><%= message.sent_at.strftime("%b %e at %l:%M %p") %></small>
       <% elsif  message.status == "received" %><small>Received</small> 
        <small><%= message.created_at.strftime("%b %e at %l:%M %p") %></small>
       <% end %> 
     </div>
  </div>
</div>

app/views/conversations/messages/_pending_message.html.erb
<div class="clearfix <%= pending_message.id %>">
  <div class="alert <%= pending_message.from ? 'alert-info message-pending' : 'alert-success message-pending' %>">
    <%= pending_message.body %>
    <div class="text-right">
      <% if pending_message.send_at.nil? %>
        <small>Will send momentarily</small>
      <% else %>  
        <small>Will send <%= pending_message.send_at.strftime("%b %e at %l:%M %p") %></small>
      <% end %>
    </div>
    <% if pending_message.recurring? %>
      <small class="dark-text italic">This message is part of a recurring series.</small>  
    <% else %>
      <%= link_to 'Delete', conversation_message_path(@conversation, pending_message), method: :delete, data: { confirm: 'Are you sure? This message will be deleted and will not be sent.' } %>
    <% end %>
  </div>
</div>

app/views/conversations/messages/index.html.erb
<div id="conversation" data-id="<%= @conversation.id %>">
  <div class="text-center h2-custom">Conversation with <%= @conversation.receiver.name %></div>

  <div class="message-box" id="message-window">
    <br>
    <div id="messages">
      <%= render @messages %>
    </div>

    <!-- Render form to send new message -->
    <%= form_for (@message), url: conversation_messages_path(@conversation) do |f| %>
    
      <div class="new-message-box">
        <div class="row">

          <div class="col-8">
            <div class="form-group">
              <%= f.text_area :body, class: 'form-control', placeholder: 'Type message here' %>
            </div>
          </div>


        </div>

        <%= f.submit 'Send Message', class: 'btn btn-primary btn-block' %>

      </div>
    <% end %>
  </div>

  <hr>

  <div>
    <span class="h3-custom">Recurring Messages</span>
    <%= link_to 'Add a Recurring Message', new_conversation_recurring_message_path(@conversation), class: 'btn btn-default pull-right' %>
  </div>

  <div class="media">
    <div class="media-body">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Message</th>
            <th>Frequency</th>
            <th>Time</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% @recurring_messages.each do |rm| %>
            <tr>
              <td><%= truncate(rm.body, length: 60) %></td>
              <td><%= rm.frequency %></td>
              <td><%= rm.start_date.strftime("%l:%M %p") %></td>
              <td><%= link_to "View Details", conversation_recurring_message_path(@conversation, rm)  %></td>
              <td><%= link_to 'Delete', conversation_recurring_message_path(@conversation, rm), method: :delete, data: { confirm: 'Are you sure? This message will be deleted and will no longer be sent moving forward.' } %></td>
            </tr>

          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <br>
  <br>

  <div class="h3-custom">Scheduled Messages</div>
  <br>
  <div id="pending-messages">
    <%= render partial: "pending_message", collection: @pending_messages %>
  </div>

</div>

<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'shared/head' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/notices' %>

    <div class="container">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/receivers/_form.html.erb
<%= form_with(model: receiver, local: true) do |form| %>
  <% if receiver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receiver.errors.count, "error") %> prohibited this receiver from being saved:</h2>

      <ul>
      <% receiver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, class: 'form-control' %>
  </div>


  <%= form.submit class: 'btn btn-primary' %>
  
<% end %>

app/views/receivers/edit.html.erb
<h1>Editing Receiver</h1>

<%= render 'form', receiver: @receiver %>

<%= link_to 'Show', @receiver %> |
<%= link_to 'Back', receivers_path %>

app/views/receivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Receivers</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receivers.each do |receiver| %>
      <tr>
        <td><%= receiver.name %></td>
        <td><%= receiver.phone_number %></td>
        <td><%= receiver.user.email %></td>
        <td><%= link_to 'Show', receiver %></td>
        <td><%= link_to 'Edit', edit_receiver_path(receiver) %></td>
        <td><%= link_to 'Destroy', receiver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receiver', new_receiver_path %>

app/views/receivers/new.html.erb
<h1>New Receiver</h1>

<%= render 'form', receiver: @receiver %>

<%= link_to 'Back', receivers_path %>

app/views/receivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @receiver.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @receiver.phone_number %>
</p>

<p>
  <strong>User:</strong>
  <%= @receiver.user.email%>
</p>

<%= link_to 'Edit', edit_receiver_path(@receiver) %> |
<%= link_to 'Back', receivers_path %>

app/views/shared/_footer.html.erb
<footer class="footer text-muted bg-light">
  <div class="container">
    <span>© <%= Date.today.year %> Your Company</span>
    <ul class="list-inline mb-0 float-right">
      <li class="list-inline-item mr-3"><%= link_to "Terms", '#' %></li>
      <li class="list-inline-item mr-3"><%= link_to "Privacy", '#' %></li>
    </ul>
  </div>
</footer>

app/views/shared/_head.html.erb
<title>Axel</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">PROJECT AXEL</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
        <li class="nav-item"><%= link_to "Receivers", receivers_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Conversations", conversations_path, class: "nav-link" %></li>
      </ul>

      <% if user_signed_in? %>
        <span class="navbar-text">You're Signed In As <%= current_user.email %> &nbsp;</span>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li></li>
        </ul>
      <% else %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        </ul>
      <% end %>

    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>">
    <div class="container">
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message %>
    </div>
  </div>
<% end %>